name: Build Windows EXE
on: [workflow_dispatch]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install --upgrade pip
          pip install pyinstaller minio urllib3 tqdm
          pyinstaller --noconfirm --clean --windowed `
            --name "S3_MinIO_Manager" `
            --icon "app.ico" `
            --add-data "s3.py;." `
            --hidden-import minio `
            --hidden-import urllib3 `
            --hidden-import tqdm `
            app.py
      - uses: actions/upload-artifact@v4
        with:
          name: S3_MinIO_Manager-win
          path: dist/S3_MinIO_Manager/**
