name: Build Windows EXE
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults: { run: { shell: pwsh } }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up venv & install deps
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install "pillow>=10.0.0" pyinstaller minio urllib3 tqdm

      - name: Prepare a valid multi-size ICO
        run: |
          .\.venv\Scripts\Activate.ps1
          # Remove any stale icon.ico that might be in the repo
          if (Test-Path icon.ico) { Remove-Item icon.ico -Force }
          # Ensure you have an icon.png in the repo (square, >=512x512)
          if (!(Test-Path icon.png)) { throw "Missing icon.png in repo root." }
          python - << 'PY'
          from PIL import Image, IcoImagePlugin
          src = "icon.png"
          im = Image.open(src).convert("RGBA")
          if im.width != im.height:
              # center-crop to square if needed
              s = min(im.width, im.height)
              x = (im.width - s)//2; y = (im.height - s)//2
              im = im.crop((x,y,x+s,y+s))
          sizes = [(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)]
          im.save("icon.ico", sizes=sizes)
          # Verify it's truly an ICO Pillow can read
          IcoImagePlugin.IcoFile(open("icon.ico","rb"))
          print("icon.ico generated and verified")
          PY

      - name: Build EXE with PyInstaller
        run: |
          .\.venv\Scripts\Activate.ps1
          pyinstaller --noconfirm --clean --windowed `
            --name "S3_MinIO_Manager" `
            --icon "icon.ico" `
            --add-data "s3.py;." `
            --hidden-import minio `
            --hidden-import urllib3 `
            --hidden-import tqdm `
            app.py

      - uses: actions/upload-artifact@v4
        with:
          name: S3_MinIO_Manager-win
          path: dist/S3_MinIO_Manager/**
